#define CLOCK_CYCLES_PER_SECOND SystemCoreClock

#define VER_NUM 0x01000000
#define BUILD_NUM 0x22061500
#define SERIAL_NUM 0xF0000001
#define MAGIC_NUM 0x424CA5A5
#define CRC_NUM 0x55667788

#define BUTTON_PORT GPIOA
#define BUTTON_PIN GPIO_PIN_0

#define PWM1_PORT GPIOA
#define PWM1_PIN GPIO_PIN_8

#define TRIGGER_PORT GPIOA
#define TRIGGER_PIN GPIO_PIN_9

#define TEST0_PORT GPIOA
#define TEST0_PIN GPIO_PIN_9

#define USART1_RX_PORT GPIOB
#define USART1_RX_PIN GPIO_PIN_3

#define PWM2_PORT GPIOB
#define PWM2_PIN GPIO_PIN_4

#define USART1_TX_PORT GPIOB
#define USART1_TX_PIN GPIO_PIN_6

#define BUZZER_PORT GPIOB
#define BUZZER_PIN GPIO_PIN_9

#define LED1_PORT GPIOC
#define LED1_PIN GPIO_PIN_13

#define PWM1_ID TIM1
#define PWM1_CHANNEL TIM_CHANNEL_1

#define PWM2_ID TIM3
#define PWM2_CHANNEL TIM_CHANNEL_1

/* AT24C02 */
#define AT24C02_DEV_ADDR 0xA0
#define AT24C02_DEV_ADDR_WRITE 0xA0
#define AT24C02_DEV_ADDR_READ 0xA1
